### ISSUE TITLE
[Question]Can set different min-instance and max-instance for pserver?

### ISSUE THREAD

**Issue by xq2005** [elasticdeeplearning/edl#17]
The example shows the min-instance and max-instance value are same for pserver.

  pserver:
    min-instance: 2
    max-instance: 2
    resources:
      ...

Can I set them into different value? Thanks.

**Comment by putcn** [comment]
yes, and you are supposed to, so that edl can dynamically and continuously adjust the count of pserver within the range you set to fit in current computing resource your cluster have.

**Comment by xq2005** [comment]
Thanks.
