### ISSUE TITLE
[request] Please update the links in README

### ISSUE THREAD

**Issue by gaocegege** [elasticdeeplearning/edl#51]
I found that some links in README are 404, I think we should update these links. For example, I am looking for docs for Fault-Tolerant Training in PaddlePaddle. But I cannot find it.

I'd appreciate it if anyone could help me.

Thanks :clinking_glasses: :beers:

**Comment by gongweibao** [comment]
The new version of EDL is testing and we will release some models use it in March.
 I will let you know when they are ready.

**Comment by gongweibao** [comment]
It's in reviewing:https://github.com/PaddlePaddle/edl/pull/65

**Comment by gaocegege** [comment]
LGTM, thanks.
